### PR TITLE
fixed dropdown when multiple inputs are needed

### LINKED ISSUE #308: selectInput doesn't recognize a single value being selected
Repro - run the following application:

```
library(shiny)
library(shiny.semantic)

ui <- semanticPage(
  uiOutput("test")
)

server <- function(input, output) {
  output$test <- renderUI({
    shiny.semantic::selectInput(
      inputId = "selected",
      label = NULL,
      choices =  c("a", "b", "c"),
      selected = c("a"),
      multiple = TRUE
    )
  })
}

shinyApp(ui = ui, server = server)
```

Expected result - "a" should be selected

Observed result - no item is selected

Doesn't work when writing `selected = "a"` either.

### PR DESCRIPTION
**Pull request by dokato**
Fixes #308 .
Contributes to #313 

A bit hacky, but this should help.

**DoD**

- [x] Major project work has a corresponding task. If there’s no task for what you are doing, create it. Each task needs to be well defined and described.

- [x] Change has been tested (manually or with automated tests), everything runs correctly and works as expected. No existing functionality is broken.

- [x] No new error or warning messages are introduced.

- [x] All interaction with a semantic functions, examples and docs are written from the perspective of the person using or receiving it. They are understandable and helpful to this person.

- [x] If the change affects code or repo sctructure, README, documentation and code comments should be updated. 

- [x] All code has been peer-reviewed before merging into any main branch.

- [x] All changes have been merged into the main branch we use for development (develop).

- [x] Continuous integration checks (linter, unit tests) are configured and passed.

- [x] Unit tests added for all new or changed logic.

- [x] All task requirements satisfied. The reviewer is responsible to verify each aspect of the task.

- [x] Any added or touched code follows our style-guide.

### CODE REVIEW

File: R/dropdown.R [hunk 1]
```diff
@@ -32,7 +32,10 @@
 #' @export
 dropdown_input <- function(input_id, choices, choices_value = choices,
                      default_text = "Select", value = NULL, type = "selection fluid") {
-    if (!is.null(value)) value <- paste(as.character(value), collapse = ",")
+    if (!is.null(value)) {
+      value <- paste(as.character(value), collapse = ",")
+      value <- paste0(value, ",")
```
Comment (krystian8207) [inline R/dropdown.R:37]: @dokato why this change solves an issue?

**Review by krystian8207 — COMMENTED** [review]
ptal at one comment

File: R/dropdown.R (hunk 1 above)
Comment (dokato) [reply R/dropdown.R:37]: I think this is due to how the split works in JS: https://github.com/Appsilon/shiny.semantic/blob/develop/inst/www/shiny-semantic-dropdown.js#L28 otherwise it is not treated as an array.

**Comment by DamianRodziewicz** [comment]
@dokato I think that the fix should be done in a different place. It looks like javascript needs to be updated to treat a single value correctly instead of hacking in an empty value as a second argument in R.

**Review by DamianRodziewicz — APPROVED** [review]
LGTM, tested

**Comment by DamianRodziewicz** [comment]
Thank you for the fix @krystian8207, works well.

As a note: Fomantic automatically sets the 'active' class so it is not needed.
