### PR TITLE
Rabii.tabsetupdate

### LINKED ISSUE #323: Is there a way to update the selected tab from `tabset()`?
When using a tabset, the `updateTabsetPanel()` doesn't work with it. The package does not provide an alternative. Is there a standard way to achieve this? Perhaps a `shiny.semantic::updateTabset()` function should be added?

### PR DESCRIPTION
**Pull request by rabiibouhestine**
Fixes #323 .

- [ ] Major project work has a corresponding task. If there’s no task for what you are doing, create it. Each task needs to be well defined and described.

- [ ] Change has been tested (manually or with automated tests), everything runs correctly and works as expected. No existing functionality is broken.

- [ ] No new error or warning messages are introduced.

- [ ] All interaction with a semantic functions, examples and docs are written from the perspective of the person using or receiving it. They are understandable and helpful to this person.

- [ ] If the change affects code or repo sctructure, README, documentation and code comments should be updated. 

- [ ] All code has been peer-reviewed before merging into any main branch.

- [ ] All changes have been merged into the main branch we use for development (develop).

- [ ] Continuous integration checks (linter, unit tests) are configured and passed.

- [ ] Unit tests added for all new or changed logic.

- [ ] All task requirements satisfied. The reviewer is responsible to verify each aspect of the task.

- [ ] Any added or touched code follows our style-guide.

### CODE REVIEW

File: examples/tabset/app.R [hunk 1]
```diff
@@ -2,28 +2,47 @@ library(shiny)
...
+    selected = "mpg",
+    width = 200
+  ),
+  br(),br(),
   tabset(tabs =
            list(
              list(menu = "First Tab", content = "Text works well", id= "first_tab"),
              list(menu = "Second Tab", content = plotOutput("plot1"), id = "second_tab"),
-             list(menu = "Third Tab", content = plotOutput("plot2"))
+             list(menu = "Third Tab", content = plotOutput("plot2"), id = "third_tab")
```
Comment (dokato) [inline examples/tabset/app.R:21]: could you remove the id here? just to show the user that this is not a mandatory field

**Review by dokato — CHANGES_REQUESTED** [review]
Tests need to be updated, and please see some minor comment. Otherwise, looks great 👍

**Review by dokato — APPROVED** [review]
👍
