### PR TITLE
Fix calendar timezone bug

### LINKED ISSUE #312: calendar changes date according to browser time zone
When updating value of `calendar` input the date is converted to local browser time zone (with the date converted to datetime where time is set to midnight). If the time zone of the value is not provided, it assumes that it is "UTC", thus if the local time zone is "UTC-X", the date will be changed to the day before. As a result, the value returned by the input will be the day before, but without the time zone (it will use "UTC" as default). 

This behavior can be reproduced by changing your local computer time (tested on Windows).

Minimal example:

`shiny`: 1.5.0
`shiny.semantic`: 0.4.0

```
library(shiny)
library(shiny.semantic)

ui <- semanticPage(
    shiny.semantic::calendar(input_id = "semantic_calendar", type = "date"),
    shiny::dateInput(inputId = "shiny_calendar", label = NULL),
    action_button(input_id = "update_date", label = "Update date to 2010-10-19")
)

server <- function(input, output, session) {
    observeEvent(input$update_date, {
        date <- "2010-10-19"
        update_calendar(
            session,
            "semantic_calendar",
            value = date
        )

        updateDateInput(
            session,
            "shiny_calendar",
            value = date
        )
    })

    observe({
        req(input$shiny_calendar)
        print("Shiny calendar:")
        print(input$shiny_calendar)
        print(lubridate::tz(input$shiny_calendar))
    })

    observe({
        req(input$semantic_calendar)
        print("Semantic calendar:")
        print(input$semantic_calendar)
        print(lubridate::tz(input$semantic_calendar))
    })
}

shinyApp(ui = ui, server = server)
```

Output:
image

### PR DESCRIPTION
**Pull request by rabiibouhestine**
Short description (with a reference to an issue).

closes #312 

**DoD**

- [ ] Major project work has a corresponding task. If there’s no task for what you are doing, create it. Each task needs to be well defined and described.

- [ ] Change has been tested (manually or with automated tests), everything runs correctly and works as expected. No existing functionality is broken.

- [ ] No new error or warning messages are introduced.

- [ ] All interaction with a semantic functions, examples and docs are written from the perspective of the person using or receiving it. They are understandable and helpful to this person.

- [ ] If the change affects code or repo sctructure, README, documentation and code comments should be updated. 

- [ ] All code has been peer-reviewed before merging into any main branch.

- [ ] All changes have been merged into the main branch we use for development (develop).

- [ ] Continuous integration checks (linter, unit tests) are configured and passed.

- [ ] Unit tests added for all new or changed logic.

- [ ] All task requirements satisfied. The reviewer is responsible to verify each aspect of the task.

- [ ] Any added or touched code follows our style-guide.

### CODE REVIEW

**Review by dokato — CHANGES_REQUESTED** [review]
Please fix tests

File: R/calendar.R [hunk 1]
```diff
@@ -53,9 +53,9 @@
 #' @rdname calendar
 #' @export
 calendar <- function(input_id, value = NULL, placeholder = NULL, type = "date", min = NA, max = NA) {
-  value <- format(as.Date(value), "%Y/%m/%d")
-  min <- format(as.Date(min), "%Y/%m/%d")
-  max <- format(as.Date(max), "%Y/%m/%d")
+  value <- if (!is.null(value)) format(as.Date(value), "%Y/%m/%d")
+  min <- if (!is.null(min)) format(as.Date(min), "%Y/%m/%d")
+  max <- if (!is.null(max)) format(as.Date(max), "%Y/%m/%d")
```
Comment (rabiibouhestine) [inline R/calendar.R:58]: shouldn't we test for na here for max and min? as that's their defaults here?

**Review by dokato — APPROVED** [review]
👍
